language: node_js
node_js:
  - "6"
  - "8"
os:
  - linux
  - osx
dist: trusty
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test -- --coverage
after_success:
  - coveralls < coverage/lcov.info
